name: Create AU Release
description: Use this template to push your code to AU environment
title: "[AU] Deployment of latest code to AU - "
labels:
  - au
assignees:
  - your-username
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Which repository you want to push
      description: You may select more than one.
      options:
        - label: KYC
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for KYC repository
            placeholder: e.g., main
        - label: HOUSEHOLD
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for HOUSEHOLD repository
            placeholder: e.g., develop
        - label: DATA
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for DATA repository
            placeholder: e.g., feature/new-data
        - label: NOTIFICATION
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for NOTIFICATION repository
            placeholder: e.g., hotfix/notification-fix
        - label: AX360
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for AX360 repository
            placeholder: e.g., release-v1.0
        - label: BFF
          branch_name_field:
            label: Branch Name
            description: Enter the branch name for BFF repository
            placeholder: e.g., bugfix/bff-bug-fix
    validations:
      required: true
 
  - type: textarea
    id: pr-description
    attributes:
      label: Pull Request Description
      description: "A detailed description of the pull request."
      placeholder: "This pull request includes the following changes..."
    validations:
      required: true
