name: Create AU Release
description: Use this template to push your code to AU environment
title: "[AU] Deployment of latest code to AU - "
labels: [au]
assignees:
  - your-username
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Which repository you want to push
      description: You may select more than one.
      options:
        - label: KYC
        - label: HOUSEHOLD
        - label: DATA
        - label: NOTIFICATION
        - label: AX360
        - label: BFF
    validations:
      required: true

  - type: input
    id: source-branch-kyc
    attributes:
      label: Source Branch for KYC
      description: "The branch to create the release branch from (e.g., `main` or `develop`)."
      placeholder: "main"

  - type: input
    id: source-branch-notification
    attributes:
      label: Source Branch for Notification
      description: "The branch to create the release branch from (e.g., `main` or `develop`)."

  - type: textarea
    id: pr-description
    attributes:
      label: Pull Request Description
      description: "A detailed description of the pull request."
      placeholder: "This pull request includes the following changes..."
    validations:
      required: true
