name: Create Release 
description: Use this template to push your code to QA enviroment
title: "[QA] deployment of latest code to qa - "
labels:
  - release
  - workflow
assignees:
  - your-username
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Which repository you want to push
      description: You may select more than one.
      options:
        - label: KYC
        - label: HOUSEHOLD
        - label: DATA
        - label: NOTIFICATION
        - label: AX360
        - label: BFF
    validations:
      required: TRUE
 
  - type: textarea
    id: pr-description
    attributes:
      label: Pull Request Description
      description: "A detailed description of the pull request."
      placeholder: "This pull request includes the following changes..."
   validations:
    required: TRUE   

