name: Create Release
description: Use this template to create a release branch from a different repository.
title: "[Release Branch Request] - "
labels:
  - release
  - workflow
assignees:
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        ## Create Release Branch
        
        Please provide the following details to create a release branch.
  - type: input
    id: source-repository
    attributes:
      label: Source Repository
      description: "The repository from which to create the release branch (e.g., `organization/repo-name`)."
      placeholder: "organization/repo-name"
  - type: input
    id: branch-name
    attributes:
      label: Branch Name
      description: "The name of the new release branch."
      placeholder: "release/v1.0.0"
  - type: checkboxes
    id: source-branch
    attributes:
      label: Source Branch
      description: "The branch to create the release branch from (please select only one)."
      options:
        - label: main
          value: main
        - label: develop
          value: develop
        - label: feature
          value: feature
        - label: hotfix
          value: hotfix
        - label: other
          value: other
