name: Create QA Release 
description: Use this template to push your code to QA environment
title: "[QA] Deployment of latest code to QA - "
labels:
  - release
  - qa
assignees:
  - your-username
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Which repository you want to push
      description: You may select more than one.
      options:
        - label: KYC
        - label: HOUSEHOLD
        - label: DATA
        - label: NOTIFICATION
        - label: AX360
        - label: BFF
    validations:
      required: true
 
  - type: textarea
    id: pr-description
    attributes:
      label: Pull Request Description
      description: "A detailed description of the pull request."
      placeholder: "This pull request includes the following changes..."
    validations:
      required: true
