name: Create Release Branch

on:
  issues:
    types: [opened]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print issue body
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"

      - name: Extract issue information
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "ISSUE_BODY content:"
          echo "$ISSUE_BODY"
          echo "Original Input:"
          echo "$ISSUE_BODY" | cat -A
          
          # Extract the section
          echo -e "\nExtracting the section:"
          SECTION=$(echo "$ISSUE_BODY" | sed -n '/^### Source Repository$/,/^$/p')
          echo "$SECTION" | cat -A
          
          # Remove the header line
          echo -e "\nRemoving the header:"
          NO_HEADER=$(echo "$SECTION" | sed '/^### Source Repository$/d')
          echo "$NO_HEADER" | cat -A
          
          # Remove empty lines
          echo -e "\nRemoving empty lines:"
          NO_EMPTY_LINES=$(echo "$NO_HEADER" | sed '/^$/d')
          echo "$NO_EMPTY_LINES" | cat -A
          
          # Trim whitespace
          echo -e "\nTrimming whitespace:"
          FINAL_RESULT=$(echo "$NO_EMPTY_LINES" | xargs)
          echo "$FINAL_RESULT" | cat -A
          
          # Assign to REPO
          REPO=$FINAL_RESULT
          echo "Extracted Source Repository: $REPO"
          
          # Extracting repository
          REPO=$(echo "$ISSUE_BODY" | sed -n '/^### Source Repository$/,/^$/ { /### Source Repository/d; /^$/d; p }' | xargs)
          
          # Extracting branch name
          NEW_BRANCH=$(echo "$ISSUE_BODY" | sed -n '/^### Branch Name$/,/^$/ { /### Branch Name/d; /^$/d; p }' | xargs)
          
          # Extracting source branch
          SOURCE_BRANCH=$(echo "$ISSUE_BODY" | sed -n '/^### Source Branch$/,/^$/ { /### Source Branch/d; /^$/d; p }' | xargs)
  
          echo "Extracted REPO: $REPO"
          echo "Extracted NEW_BRANCH: $NEW_BRANCH"
          echo "Extracted SOURCE_BRANCH: $SOURCE_BRANCH"

          # Set environment variables
          echo "SOURCE_REPOSITORY=$REPO" >> $GITHUB_ENV
          echo "BRANCH_NAME=$NEW_BRANCH" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV

      - name: Print extracted variables
        run: |
          echo "SOURCE_REPOSITORY=${{ env.SOURCE_REPOSITORY }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "SOURCE_BRANCH=${{ env.SOURCE_BRANCH }}"

      - name: Create release branch
        run: |
          # Clone the source repository
          git clone https://github.com/${{ env.SOURCE_REPOSITORY }} repo
          cd repo

          # Checkout the source branch
          git checkout ${{ env.SOURCE_BRANCH }}

          # Create and checkout the new release branch
          git checkout -b ${{ env.BRANCH_NAME }}

          # Push the new branch to origin
          git push origin ${{ env.BRANCH_NAME }}

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BRANCH_TOKEN }}
