name: Create Release Branch

on:
  issues:
    types: [opened]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print issue body
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"

      - name: Extract issue information
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          REPO=$(echo "$ISSUE_BODY" | awk -F '### Source Repository' '{print $2}' | awk -F '###' '{print $1}' | xargs)
          NEW_BRANCH=$(echo "$ISSUE_BODY" | awk -F '### Branch Name' '{print $2}' | awk -F '###' '{print $1}' | xargs)
          SOURCE_BRANCH=$(echo "$ISSUE_BODY" | awk -F '### Source Branch' '{print $2}' | awk -F '###' '{print $1}' | xargs)

          echo "Extracted REPO: $REPO"
          echo "Extracted NEW_BRANCH: $NEW_BRANCH"
          echo "Extracted SOURCE_BRANCH: $SOURCE_BRANCH"

          echo "SOURCE_REPOSITORY=$REPO" >> $GITHUB_ENV
          echo "BRANCH_NAME=$NEW_BRANCH" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV

      - name: Print extracted variables
        run: |
          echo "SOURCE_REPOSITORY=${{ env.SOURCE_REPOSITORY }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "SOURCE_BRANCH=${{ env.SOURCE_BRANCH }}"

      - name: Create release branch
        run: |
          git clone https://github.com/${{ env.SOURCE_REPOSITORY }} repo
          cd repo
          git checkout ${{ env.SOURCE_BRANCH }}
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BRANCH_TOKEN }}
