name: Create Release Branch

on:
  issues:
    types: [opened]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Extract issue information
        id: extract
        run: |
          echo "REPO=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=Source Repository:\n).*' | sed 's/\r$//')" >> $GITHUB_ENV
          echo "NEW_BRANCH=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=Branch Name:\n).*' | sed 's/\r$//')" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=Source Branch:\n).*' | sed 's/\r$//')" >> $GITHUB_ENV
      

      - name: Print extracted variables
        run: |
          echo "REPO=${{ env.SOURCE_REPOSITORY }}"
          echo "NEW_BRANCH=${{ env.BRANCH_NAME }}"
          echo "SOURCE_BRANCH=${{ env.SOURCE_BRANCH }}"

      - name: Create release branch
        run: |
          git clone https://github.com/${{ env.SOURCE_REPOSITORY }} repo
          cd repo
          git checkout ${{ env.SOURCE_BRANCH }}
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BRANCH_TOKEN }}
 
