name: Create Release Branch

on:
  issues:
    types: [opened]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print issue body
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"

      - name: Extract issue information
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "ISSUE_BODY content:"
          echo "$ISSUE_BODY"

          # Convert issue body to JSON format
          ISSUE_JSON=$(echo "$ISSUE_BODY" | jq -R -s 'split("\n") | map(select(. != ""))')

          # Extracting repository
          REPO=$(echo "$ISSUE_JSON" | jq -r 'index("### Source Repository") as $idx | .[$idx + 1]')

          # Extracting branch name
          NEW_BRANCH=$(echo "$ISSUE_JSON" | jq -r 'index("### Branch Name") as $idx | .[$idx + 1]')

          # Extracting source branch
          SOURCE_BRANCH=$(echo "$ISSUE_JSON" | jq -r 'index("### Source Branch") as $idx | .[$idx + 1]')

          echo "Extracted REPO: $REPO"
          echo "Extracted NEW_BRANCH: $NEW_BRANCH"
          echo "Extracted SOURCE_BRANCH: $SOURCE_BRANCH"

          # Set environment variables
          echo "SOURCE_REPOSITORY=$REPO" >> $GITHUB_ENV
          echo "BRANCH_NAME=$NEW_BRANCH" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV

      - name: Print extracted variables
        run: |
          echo "SOURCE_REPOSITORY=${{ env.SOURCE_REPOSITORY }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "SOURCE_BRANCH=${{ env.SOURCE_BRANCH }}"

      - name: Create release branch
        run: |
          # Clone the source repository
          git clone https://github.com/${{ env.SOURCE_REPOSITORY }} repo
          cd repo

          # Checkout the source branch
          git checkout ${{ env.SOURCE_BRANCH }}

          # Create and checkout the new release branch
          git checkout -b ${{ env.BRANCH_NAME }}

          # Push the new branch to origin
          git push origin ${{ env.BRANCH_NAME }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
