name: Create Release Branch

on:
  issues:
    types: [opened]
    labels: [release]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get issue details
        id: get-issue-details
        uses: octokit/rest@v18  # Check for typos (e.g., octokit/rest)
        with:
          issue-number: ${{ github.issue.number }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repo }}

      - name: Extract release information
        id: extract-release-info
        run: |
          source_repo=$(echo ${{ steps.get-issue-details.outputs.data.body }} | grep -Eo 'organization/[^"]+')
          branch_name=$(echo ${{ steps.get-issue-details.outputs.data.body }} | grep -Eo 'release\/v[0-9]+\.[0-9]+\.[0-9]+')
          source_branch=$(echo ${{ steps.get-issue-details.outputs.data.body }} | grep -Eo 'main|develop')

          if [[ -z "$source_repo" || -z "$branch_name" || -z "$source_branch" ]]; then
            echo "Error: Missing required information in issue body. Please provide:"
            echo "* Source Repository (e.g., organization/repo-name)"
            echo "* Branch Name (e.g., release/v1.0.0)"
            echo "* Source Branch (e.g., main or develop)"
            exit 1
          fi

          echo "SOURCE_REPO=$source_repo" >> $GITHUB_ENV  # Ensure proper environment variable setting
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$source_branch" >> $GITHUB_ENV

      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          repo: ${{ env.SOURCE_REPO }}
          ref: ${{ env.SOURCE_BRANCH }}

      - name: Create release branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}
