name: Create Incremented Tag

on:
  issues:
    types: [opened]

jobs:
  create-incremented-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print issue body
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"

      - name: Extract issue information
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "ISSUE_BODY content:"
          echo "$ISSUE_BODY"

          # Convert issue body to JSON format
          ISSUE_JSON=$(echo "$ISSUE_BODY" | jq -R -s 'split("\n") | map(select(. != ""))')

          # Extracting repository
          REPO=$(echo "$ISSUE_JSON" | jq -r 'index("### Source Repository") as $idx | .[$idx + 1]')

          # Extracting branch name
          NEW_BRANCH=$(echo "$ISSUE_JSON" | jq -r 'index("### Branch Name") as $idx | .[$idx + 1]')

          # Extracting source branch
          SOURCE_BRANCH=$(echo "$ISSUE_JSON" | jq -r 'index("### Source Branch") as $idx | .[$idx + 1]')

          echo "Extracted REPO: $REPO"
          echo "Extracted NEW_BRANCH: $NEW_BRANCH"
          echo "Extracted SOURCE_BRANCH: $SOURCE_BRANCH"

          # Set environment variables
          echo "SOURCE_REPOSITORY=$REPO" >> $GITHUB_ENV
          echo "BRANCH_NAME=$NEW_BRANCH" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV

      - name: Print extracted variables
        run: |
          echo "SOURCE_REPOSITORY=${{ env.SOURCE_REPOSITORY }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "SOURCE_BRANCH=${{ env.SOURCE_BRANCH }}"

      - name: Set up Git
        run: |
          git config --global credential.helper store
          git config --global user.email "jainrv0510@gmail.com"
          git config --global user.name "rvjain0510"

      - name: Clone target repository and extract tag
        run: |
          # Clone the target repository
          git clone https://${{ secrets.TESTY }}@github.com/test-workflow-dep target-repo
          cd target-repo

          # Install yq
          sudo apt-get update && sudo apt-get install -y yq

          # Extract the tag from the YAML file
          TAG=$(yq e '.apps[] | select(.name == "ax360-bff") | .tag' test.yaml)
          echo "Extracted tag: $TAG"

          # Split the tag into components
          IFS='.' read -r -a TAG_PARTS <<< "$TAG"
          MAJOR=${TAG_PARTS[0]}
          MINOR=${TAG_PARTS[1]}
          PATCH=${TAG_PARTS[2]}

          # Increment the patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New tag: $NEW_TAG"

          # Set environment variables
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Clone source repository and create new tag
        run: |
          # Clone the source repository
          git clone https://${{ secrets.TESTY }}@github.com/${{ github.repository }} source-repo
          cd source-repo

          # Checkout the source branch
          git checkout ${{ env.SOURCE_BRANCH }}

          # Create a new tag
          git tag ${{ env.NEW_TAG }}

          # Push the new tag to origin
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.TESTY }}
